KillMultiplier: 20
#A multiplier of 1 means 1 point for 1 kill
DamageMultiplier: 1
#A multiplier of 1 means 1 point for 1 heart of damage


SurvivalMultiplier: 3
#A multiplier of 1 means 1 point for 1 player who dies before you



